import { useState, useEffect, useCallback } from "react";
import {
  Zap,
  LayoutDashboard,
  Users,
  Plus,
  X,
  CheckCircle2,
  Circle,
  Lock,
  Clock,
  PenLine,
  FileText,
  Film,
  Shield,
  ChevronRight,
  AlertCircle,
  Sparkles,
  ClipboardList,
  Loader2,
  RefreshCw,
  LogOut,
  Mail,
  Eye,
  EyeOff,
  Key,
  ArrowRight,
} from "lucide-react";


/*
  NEON CLASSES — TASK TRACKER (Wired to FastAPI Backend)
  Blueprint coverage:
  §1 Layout .......... fixed left sidebar + sticky header + scrollable main, dark neon theme
  §2 Schema .......... Roles / Users / Tasks / Steps served dynamically via REST API
  §3 RBAC ............ Admin sees all tasks; workers see only assigned tasks & checklists
  §4 Workflows ....... 13 steps (4 Script + 4 Content + 5 Video) auto-generated by backend
  §5 Create Task ..... Admin-only modal, title/description + 3 role assignments
  §6 Dashboard ....... Task cards with overall progress, role step counters, and status badges
  §7 Step Tracker .... Strict sequential locking enforced by server and indicated in UI
  §8 Notifications ... Real-time feedback toasts, automatic DONE status on 13/13 completion
*/

function getApiBase() {
  if (typeof window !== "undefined") {
    const saved = localStorage.getItem("NEON_API_BASE");
    if (saved) return saved.replace(/\/+$/, "");
  }
  const rawApiBase = import.meta.env.VITE_API_BASE !== undefined
    ? import.meta.env.VITE_API_BASE
    : "http://localhost:8000";
  return rawApiBase ? rawApiBase.replace(/\/+$/, "") : "";
}

/* ---------------------------------------------------------------- */
/* UI-only Constants & Metadata                                     */
/* ---------------------------------------------------------------- */

const WORKER_ROLES = ["SCRIPT_WRITER", "CONTENT_WRITER", "VIDEO_EDITOR"];

const ROLE_META = {
  ADMIN: {
    label: "Admin",
    icon: Shield,
    text: "text-cyan-300",
    bg: "bg-cyan-950",
    border: "border-cyan-800",
  },
  SCRIPT_WRITER: {
    label: "Script Writer",
    icon: PenLine,
    text: "text-violet-300",
    bg: "bg-violet-950",
    border: "border-violet-800",
  },
  CONTENT_WRITER: {
    label: "Content Writer",
    icon: FileText,
    text: "text-amber-300",
    bg: "bg-amber-950",
    border: "border-amber-800",
  },
  VIDEO_EDITOR: {
    label: "Video Editor",
    icon: Film,
    text: "text-rose-300",
    bg: "bg-rose-950",
    border: "border-rose-800",
  },
};

const WORKFLOWS_DISPLAY = {
  SCRIPT_WRITER: 4,
  CONTENT_WRITER: 4,
  VIDEO_EDITOR: 5,
};

const STATUS_META = {
  TODO: {
    label: "To-Do",
    cls: "bg-zinc-900 text-zinc-300 border-zinc-700",
    dot: "bg-zinc-400",
  },
  IN_PROGRESS: {
    label: "In Progress",
    cls: "bg-amber-950 text-amber-300 border-amber-800",
    dot: "bg-amber-400",
  },
  DONE: {
    label: "Done",
    cls: "bg-emerald-950 text-emerald-300 border-emerald-800",
    dot: "bg-emerald-400",
  },
};

const PREDEFINED_ACCOUNTS = [
  {
    role: "ADMIN",
    label: "Admin",
    name: "Raja Sir",
    email: "admin@neonclasses.com",
    password: "admin123",
    badge: "Admin Access",
    tagline: "Full access to all tasks, team members & assignments",
    redirectUrl: "#/admin",
    icon: Shield,
    border: "border-cyan-500/40 hover:border-cyan-400",
    bg: "bg-cyan-950/40",
    text: "text-cyan-300",
    accent: "bg-cyan-500",
  },
  {
    role: "SCRIPT_WRITER",
    label: "Script Writer",
    name: "Priya Sharma",
    email: "priya@neonclasses.com",
    password: "priya123",
    badge: "Employee",
    tagline: "4 sequential steps: outline, draft, review & final approval",
    redirectUrl: "#/employee",
    icon: PenLine,
    border: "border-violet-500/40 hover:border-violet-400",
    bg: "bg-violet-950/40",
    text: "text-violet-300",
    accent: "bg-violet-500",
  },
  {
    role: "CONTENT_WRITER",
    label: "Content Writer",
    name: "Neha Gupta",
    email: "neha@neonclasses.com",
    password: "neha123",
    badge: "Employee",
    tagline: "4 sequential steps: questions, explanations & formatting",
    redirectUrl: "#/employee",
    icon: FileText,
    border: "border-amber-500/40 hover:border-amber-400",
    bg: "bg-amber-950/40",
    text: "text-amber-300",
    accent: "bg-amber-500",
  },
  {
    role: "VIDEO_EDITOR",
    label: "Video Editor",
    name: "Karan Singh",
    email: "karan@neonclasses.com",
    password: "karan123",
    badge: "Employee",
    tagline: "5 sequential steps: assets, animation, render & export",
    redirectUrl: "#/employee",
    icon: Film,
    border: "border-rose-500/40 hover:border-rose-400",
    bg: "bg-rose-950/40",
    text: "text-rose-300",
    accent: "bg-rose-500",
  },
];


/* ---------------------------------------------------------------- */
/* API Client Helper                                                */
/* ---------------------------------------------------------------- */

async function apiFetch(path, token, options = {}) {
  const base = getApiBase();
  const url = `${base}${path}`;
  const res = await fetch(url, {

    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(options.headers || {}),
    },
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(data.detail || `Request failed (${res.status})`);
    err.status = res.status;
    throw err;
  }
  return data;
}

/* ---------------------------------------------------------------- */
/* Helpers                                                          */
/* ---------------------------------------------------------------- */

const initials = (name) =>
  name ? name.split(" ").map((w) => w[0]).join("").slice(0, 2).toUpperCase() : "?";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const fmtDT = (d) => {
  if (!d) return "";
  const dt = new Date(d);
  if (isNaN(dt.getTime())) return "";
  let h = dt.getHours();
  const am = h >= 12 ? "PM" : "AM";
  h = h % 12 || 12;
  const m = String(dt.getMinutes()).padStart(2, "0");
  return `${dt.getDate()} ${MONTHS[dt.getMonth()]}, ${h}:${m} ${am}`;
};

const clamp2 = {
  display: "-webkit-box",
  WebkitLineClamp: 2,
  WebkitBoxOrient: "vertical",
  overflow: "hidden",
};

const CSS = `
@keyframes toastIn { from { opacity: 0; transform: translateY(10px) scale(.97); } to { opacity: 1; transform: translateY(0) scale(1); } }
* { scrollbar-width: thin; scrollbar-color: #3f3f46 transparent; }
*::-webkit-scrollbar { width: 8px; height: 8px; }
*::-webkit-scrollbar-thumb { background: #3f3f46; border-radius: 8px; }
*::-webkit-scrollbar-track { background: transparent; }
select option { background: #0a0a0a; color: #e5e5e5; }
`;

/* ---------------------------------------------------------------- */
/* Shared Presentational Components                                 */
/* ---------------------------------------------------------------- */

function Avatar({ user, className = "h-8 w-8 text-xs" }) {
  if (!user) return <div className={`${className} rounded-full bg-neutral-800 shrink-0`} />;
  const m = ROLE_META[user.role] || ROLE_META.ADMIN;
  return (
    <div
      className={`${className} rounded-full flex items-center justify-center font-bold border shrink-0 ${m.bg} ${m.text} ${m.border}`}
    >
      {initials(user.name)}
    </div>
  );
}

function Badge({ status }) {
  const m = STATUS_META[status] || STATUS_META.TODO;
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold whitespace-nowrap ${m.cls}`}
    >
      <span className={`h-1.5 w-1.5 rounded-full ${m.dot}`} />
      {m.label}
    </span>
  );
}

function Progress({ pct }) {
  return (
    <div className="h-2 rounded-full bg-neutral-800 overflow-hidden">
      <div
        className={`h-full rounded-full transition-all duration-500 ${
          pct === 100 ? "bg-emerald-400" : "bg-gradient-to-r from-cyan-500 to-cyan-300"
        }`}
        style={{ width: `${pct}%` }}
      />
    </div>
  );
}

/* ---------------------------------------------------------------- */
/* Toasts Notification Stack                                        */
/* ---------------------------------------------------------------- */

const TOAST_META = {
  success: {
    icon: CheckCircle2,
    box: "bg-emerald-950 border-emerald-800",
    ic: "text-emerald-400",
    title: "text-emerald-100",
    msg: "text-emerald-300",
  },
  error: {
    icon: AlertCircle,
    box: "bg-red-950 border-red-800",
    ic: "text-red-400",
    title: "text-red-100",
    msg: "text-red-300",
  },
  done: {
    icon: Sparkles,
    box: "bg-cyan-950 border-cyan-800",
    ic: "text-cyan-300",
    title: "text-cyan-100",
    msg: "text-cyan-300",
  },
  info: {
    icon: AlertCircle,
    box: "bg-neutral-900 border-neutral-700",
    ic: "text-neutral-300",
    title: "text-neutral-100",
    msg: "text-neutral-400",
  },
};

function ToastStack({ toasts }) {
  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 w-80 max-w-full pointer-events-none">
      {toasts.map((t) => {
        const m = TOAST_META[t.type] || TOAST_META.info;
        const Icon = m.icon;
        return (
          <div
            key={t.id}
            className={`pointer-events-auto flex items-start gap-3 rounded-xl border shadow-2xl p-3.5 ${m.box}`}
            style={{ animation: "toastIn .25s ease-out" }}
          >
            <Icon size={17} className={`${m.ic} shrink-0 mt-0.5`} />
            <div className="min-w-0">
              <div className={`text-sm font-semibold leading-tight ${m.title}`}>{t.title}</div>
              {t.msg && <div className={`text-xs mt-0.5 leading-snug ${m.msg}`}>{t.msg}</div>}
            </div>
          </div>
        );
      })}
    </div>
  );
}

/* ---------------------------------------------------------------- */
/* §7 Sequential Step Tracker (Per-Role Checklist)                  */
/* ---------------------------------------------------------------- */

function RoleChecklist({ task, role, getUserById, onToggle, busyStepId }) {
  const m = ROLE_META[role] || ROLE_META.ADMIN;
  const Icon = m.icon;
  const assigneeId = task.assignments?.[role];
  const assignee = getUserById(assigneeId);
  const steps = (task.steps || [])
    .filter((s) => s.role === role)
    .sort((a, b) => a.stepNumber - b.stepNumber);
  const done = steps.filter((s) => s.status === "DONE").length;

  return (
    <section className="rounded-xl border border-neutral-800 bg-neutral-950 overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-800">
        <div className="flex items-center gap-2.5">
          <span className={`p-1.5 rounded-lg border ${m.bg} ${m.border}`}>
            <Icon size={14} className={m.text} />
          </span>
          <div>
            <div className="text-sm font-semibold">{m.label}</div>
            <div className="text-xs text-neutral-500">{assignee ? assignee.name : "Unassigned"}</div>
          </div>
        </div>
        <span
          className={`text-xs font-semibold ${
            done === steps.length ? "text-emerald-300" : "text-neutral-400"
          }`}
        >
          {done}/{steps.length}
        </span>
      </div>

      <div className="p-2">
        {steps.map((s) => {
          const blocked =
            s.status === "PENDING" &&
            steps.some((x) => x.stepNumber < s.stepNumber && x.status !== "DONE");
          const isBusy = busyStepId === s.id;
          return (
            <button
              key={s.id}
              disabled={isBusy}
              onClick={() => onToggle(task.id, s.id)}
              className={`group w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors ${
                blocked ? "opacity-40 cursor-not-allowed" : "hover:bg-neutral-900"
              } ${isBusy ? "opacity-60" : ""}`}
            >
              {isBusy ? (
                <Loader2 size={18} className="text-cyan-400 shrink-0 animate-spin" />
              ) : s.status === "DONE" ? (
                <CheckCircle2 size={18} className="text-emerald-400 shrink-0" />
              ) : blocked ? (
                <Lock size={16} className="text-neutral-500 shrink-0" />
              ) : (
                <Circle size={18} className="text-cyan-500 shrink-0" />
              )}

              <span className="flex-1 min-w-0">
                <span
                  className={`text-sm ${
                    s.status === "DONE" ? "line-through text-neutral-500" : "text-neutral-200"
                  }`}
                >
                  {s.stepNumber}. {s.title}
                </span>
              </span>

              {s.status === "DONE" ? (
                <span className="text-xs text-neutral-500 flex items-center gap-1 shrink-0">
                  <Clock size={11} /> {fmtDT(s.completedAt)}
                </span>
              ) : (
                !blocked && (
                  <span className="text-xs text-cyan-400 font-medium shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    Mark done
                  </span>
                )
              )}
            </button>
          );
        })}
      </div>
    </section>
  );
}

/* ---------------------------------------------------------------- */
/* Task Details Modal                                               */
/* ---------------------------------------------------------------- */

function TaskDetailsModal({ task, me, isAdmin, getUserById, onClose, onToggle, busyStepId }) {
  const rolesToShow = isAdmin ? WORKER_ROLES : [me?.role].filter(Boolean);
  const doneSteps = (task.steps || []).filter((s) => s.status === "DONE").length;
  const totalSteps = task.steps?.length || 13;
  const pct = Math.round((doneSteps / totalSteps) * 100);

  return (
    <div
      className="fixed inset-0 z-40 flex items-end sm:items-center justify-center sm:p-6"
      onClick={onClose}
    >
      <div
        className="absolute inset-0"
        style={{ background: "rgba(0,0,0,0.7)", backdropFilter: "blur(4px)" }}
      />
      <div
        onClick={(e) => e.stopPropagation()}
        className="relative w-full sm:max-w-2xl bg-neutral-900 border border-neutral-800 rounded-t-2xl sm:rounded-2xl shadow-2xl overflow-hidden flex flex-col"
        style={{ maxHeight: "88vh" }}
      >
        <div className="flex items-start justify-between gap-4 p-5 border-b border-neutral-800 shrink-0">
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1.5">
              <Badge status={task.status} />
              <span className="text-xs text-neutral-500 flex items-center gap-1">
                <Clock size={12} /> Created {fmtDT(task.createdAt)}
              </span>
            </div>
            <h2 className="text-lg font-bold tracking-tight leading-snug">{task.title}</h2>
            {task.description && (
              <p className="text-sm text-neutral-400 mt-1 leading-relaxed">{task.description}</p>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-neutral-800 text-neutral-400 hover:text-neutral-100 shrink-0"
          >
            <X size={18} />
          </button>
        </div>

        <div className="px-5 pt-4 shrink-0">
          <div className="flex justify-between text-xs mb-1.5">
            <span className="text-neutral-500">Overall progress — all roles</span>
            <span className={`font-semibold ${pct === 100 ? "text-emerald-300" : "text-cyan-300"}`}>
              {doneSteps}/{totalSteps} · {pct}%
            </span>
          </div>
          <Progress pct={pct} />
        </div>

        <div className="p-5 space-y-4 overflow-y-auto">
          {rolesToShow.map((role) => (
            <RoleChecklist
              key={role}
              task={task}
              role={role}
              getUserById={getUserById}
              onToggle={onToggle}
              busyStepId={busyStepId}
            />
          ))}
          <p className="text-xs text-neutral-600 flex items-center gap-1.5">
            <Lock size={12} /> Steps unlock strictly in order. Ticking the final step auto-marks the task Done.
          </p>
        </div>
      </div>
    </div>
  );
}

/* ---------------------------------------------------------------- */
/* §5 Create Task Modal (Admin Only)                                */
/* ---------------------------------------------------------------- */

function CreateTaskModal({ users, onClose, onCreate, pushToast, creating }) {
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");
  const [asg, setAsg] = useState({ SCRIPT_WRITER: "", CONTENT_WRITER: "", VIDEO_EDITOR: "" });

  const inputCls =
    "w-full rounded-lg bg-neutral-950 border border-neutral-700 px-3 py-2 text-sm text-neutral-100 placeholder-neutral-600 outline-none focus:border-cyan-500 transition-colors";

  const submit = () => {
    if (!title.trim()) {
      pushToast("error", "Title required", "Give the task a title before creating it.");
      return;
    }
    const missing = WORKER_ROLES.find((r) => !asg[r]);
    if (missing) {
      pushToast("error", "Assignment missing", `Select a ${ROLE_META[missing].label} for this task.`);
      return;
    }
    onCreate(title.trim(), desc.trim(), { ...asg });
  };

  return (
    <div
      className="fixed inset-0 z-40 flex items-end sm:items-center justify-center sm:p-6"
      onClick={onClose}
    >
      <div
        className="absolute inset-0"
        style={{ background: "rgba(0,0,0,0.7)", backdropFilter: "blur(4px)" }}
      />
      <div
        onClick={(e) => e.stopPropagation()}
        className="relative w-full sm:max-w-lg bg-neutral-900 border border-neutral-800 rounded-t-2xl sm:rounded-2xl shadow-2xl overflow-y-auto"
        style={{ maxHeight: "88vh" }}
      >
        <div className="flex items-center justify-between p-5 border-b border-neutral-800">
          <h2 className="text-base font-bold tracking-tight">Create new task</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-neutral-800 text-neutral-400 hover:text-neutral-100"
          >
            <X size={18} />
          </button>
        </div>

        <div className="p-5 space-y-4">
          <div>
            <label className="block text-xs font-semibold uppercase tracking-widest text-neutral-400 mb-1.5">
              Title
            </label>
            <input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Ch.7 Decimals — Animated Episode"
              className={inputCls}
            />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-widest text-neutral-400 mb-1.5">
              Description
            </label>
            <textarea
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
              rows={3}
              placeholder="What is this project about?"
              className={inputCls}
            />
          </div>

          <div className="space-y-3 pt-1">
            <div className="text-xs font-semibold uppercase tracking-widest text-neutral-400">
              Assign the team
            </div>
            {WORKER_ROLES.map((role) => {
              const m = ROLE_META[role];
              const Icon = m.icon;
              const opts = users.filter((u) => u.role === role);
              return (
                <div key={role}>
                  <label className={`flex items-center gap-1.5 text-xs mb-1.5 ${m.text}`}>
                    <Icon size={12} /> {m.label}
                  </label>
                  <select
                    value={asg[role]}
                    onChange={(e) => setAsg((p) => ({ ...p, [role]: e.target.value }))}
                    className={inputCls}
                  >
                    <option value="">Select {m.label}…</option>
                    {opts.map((u) => (
                      <option key={u.id} value={u.id}>
                        {u.name}
                      </option>
                    ))}
                  </select>
                </div>
              );
            })}
          </div>

          <p className="text-xs text-neutral-500 flex items-center gap-1.5 pt-1">
            <Sparkles size={12} className="text-cyan-400" /> 13 sub-steps (4 + 4 + 5) are auto-generated
            the moment you create this task.
          </p>
        </div>

        <div className="flex justify-end gap-2 p-5 border-t border-neutral-800">
          <button
            onClick={onClose}
            className="rounded-lg border border-neutral-700 px-4 py-2 text-sm font-medium text-neutral-300 hover:bg-neutral-800 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={submit}
            disabled={creating}
            className="rounded-lg bg-cyan-500 hover:bg-cyan-400 disabled:opacity-60 px-4 py-2 text-sm font-semibold text-neutral-950 transition-colors flex items-center gap-2"
            style={{ boxShadow: "0 0 24px rgba(34,211,238,0.25)" }}
          >
            {creating && <Loader2 size={14} className="animate-spin" />}
            Create task
          </button>
        </div>
      </div>
    </div>
  );
}

/* ---------------------------------------------------------------- */
/* §6 Task Card                                                     */
/* ---------------------------------------------------------------- */

function TaskCard({ task, getUserById, onOpen }) {
  const steps = task.steps || [];
  const doneSteps = steps.filter((s) => s.status === "DONE").length;
  const pct = Math.round((doneSteps / (steps.length || 1)) * 100);

  return (
    <button
      onClick={onOpen}
      className="group text-left rounded-2xl border border-neutral-800 bg-neutral-900 p-5 hover:border-neutral-600 transition-colors flex flex-col gap-4"
    >
      <div className="flex items-start justify-between gap-3">
        <h3 className="font-semibold leading-snug tracking-tight group-hover:text-cyan-300 transition-colors">
          {task.title}
        </h3>
        <Badge status={task.status} />
      </div>

      {task.description && (
        <p className="text-sm text-neutral-400 leading-relaxed" style={clamp2}>
          {task.description}
        </p>
      )}

      <div>
        <div className="flex justify-between text-xs mb-1.5">
          <span className="text-neutral-500">
            {doneSteps}/{steps.length} steps
          </span>
          <span className={`font-semibold ${pct === 100 ? "text-emerald-300" : "text-cyan-300"}`}>
            {pct}%
          </span>
        </div>
        <Progress pct={pct} />
      </div>

      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-3 flex-wrap">
          {WORKER_ROLES.map((r) => {
            const m = ROLE_META[r];
            const Icon = m.icon;
            const rs = steps.filter((s) => s.role === r);
            const d = rs.filter((s) => s.status === "DONE").length;
            return (
              <span
                key={r}
                className={`flex items-center gap-1 text-xs ${
                  d === rs.length ? "text-emerald-300" : "text-neutral-500"
                }`}
              >
                <Icon size={12} className={m.text} /> {d}/{rs.length}
              </span>
            );
          })}
        </div>
        <div className="flex -space-x-2">
          {WORKER_ROLES.map((r) => {
            const u = getUserById(task.assignments?.[r]);
            return u ? <Avatar key={r} user={u} className="h-6 w-6 text-xs" /> : null;
          })}
        </div>
      </div>

      <div className="flex items-center justify-between text-xs text-neutral-600 border-t border-neutral-800 pt-3">
        <span className="flex items-center gap-1">
          <Clock size={12} /> {fmtDT(task.createdAt)}
        </span>
        <span className="flex items-center gap-1 text-neutral-500 group-hover:text-cyan-300 transition-colors">
          Open <ChevronRight size={14} />
        </span>
      </div>
    </button>
  );
}

/* ---------------------------------------------------------------- */
/* §0 Sign In Page (Role-Based Authentication & Predefined Accounts) */
/* ---------------------------------------------------------------- */

function SignInPage({
  onLogin,
  loading,
  error,
  clearError,
  customApiBase,
  setCustomApiBase,
  onSaveApiBase,
}) {
  const [email, setEmail] = useState("admin@neonclasses.com");
  const [password, setPassword] = useState("admin123");
  const [showPassword, setShowPassword] = useState(false);
  const [activePreset, setActivePreset] = useState("admin@neonclasses.com");
  const [showApiConfig, setShowApiConfig] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!email.trim() || !password.trim()) return;
    onLogin(email.trim(), password.trim());
  };

  const handleSelectPreset = (acc) => {
    setActivePreset(acc.email);
    setEmail(acc.email);
    setPassword(acc.password);
    clearError?.();
  };

  const handleQuickLogin = (acc) => {
    setActivePreset(acc.email);
    setEmail(acc.email);
    setPassword(acc.password);
    onLogin(acc.email, acc.password);
  };

  const currentApi = getApiBase();

  return (
    <div className="min-h-screen flex flex-col justify-center items-center bg-neutral-950 text-neutral-100 p-4 sm:p-6 relative overflow-hidden">
      {/* Background ambient lighting */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[650px] h-[350px] bg-cyan-500/10 rounded-full blur-[130px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-[450px] h-[300px] bg-violet-500/10 rounded-full blur-[130px] pointer-events-none" />

      <div className="w-full max-w-lg z-10 flex flex-col items-center">
        {/* Brand Header */}
        <div className="flex flex-col items-center text-center mb-6">
          <div
            className="h-14 w-14 rounded-2xl bg-cyan-500 text-neutral-950 flex items-center justify-center mb-3 shadow-2xl"
            style={{ boxShadow: "0 0 35px rgba(34,211,238,0.45)" }}
          >
            <Zap size={28} strokeWidth={2.5} />
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
            NEON CLASSES
          </h1>
          <p className="text-xs sm:text-sm text-neutral-400 mt-1 max-w-sm">
            Production Task Tracker & 13-Step Workflow Automation
          </p>
          <div className="inline-flex items-center gap-2 mt-3 px-3 py-1 rounded-full bg-neutral-900 border border-neutral-800 text-[11px] text-neutral-400">
            <span className="h-1.5 w-1.5 rounded-full bg-cyan-400 animate-pulse" />
            <span>
              Role-Based Routing: <strong>Admin</strong> redirects to <code className="text-cyan-300">#/admin</code> · <strong>Employee</strong> to <code className="text-violet-300">#/employee</code>
            </span>
          </div>
        </div>

        {/* Login Card */}
        <div className="w-full bg-neutral-900/90 border border-neutral-800/80 rounded-2xl p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-5">
          {error && (
            <div className="flex items-start gap-3 p-3.5 rounded-xl bg-red-950/70 border border-red-800/80 text-red-200 text-xs">
              <AlertCircle size={16} className="text-red-400 shrink-0 mt-0.5" />
              <div>
                <div className="font-semibold text-red-300">Authentication Failed</div>
                <div>{error}</div>
              </div>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-neutral-400 mb-1.5">
                Email Address
              </label>
              <div className="relative">
                <Mail size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-neutral-500" />
                <input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => {
                    setEmail(e.target.value);
                    clearError?.();
                  }}
                  placeholder="name@neonclasses.com"
                  className="w-full bg-neutral-950 border border-neutral-700/80 rounded-xl pl-10 pr-3.5 py-2.5 text-sm text-neutral-100 placeholder-neutral-600 focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 outline-none transition-all"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-neutral-400 mb-1.5">
                Password
              </label>
              <div className="relative">
                <Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-neutral-500" />
                <input
                  type={showPassword ? "text" : "password"}
                  required
                  value={password}
                  onChange={(e) => {
                    setPassword(e.target.value);
                    clearError?.();
                  }}
                  placeholder="••••••••"
                  className="w-full bg-neutral-950 border border-neutral-700/80 rounded-xl pl-10 pr-10 py-2.5 text-sm text-neutral-100 placeholder-neutral-600 focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 outline-none transition-all"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3.5 top-1/2 -translate-y-1/2 text-neutral-500 hover:text-neutral-300"
                >
                  {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full mt-2 flex items-center justify-center gap-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 disabled:opacity-60 text-neutral-950 font-bold py-3 text-sm transition-all"
              style={{ boxShadow: "0 0 25px rgba(34,211,238,0.3)" }}
            >
              {loading ? (
                <>
                  <Loader2 size={16} className="animate-spin" /> Signing in…
                </>
              ) : (
                <>
                  <span>Sign In</span>
                  <ArrowRight size={16} />
                </>
              )}
            </button>
          </form>

          {/* Predefined Accounts Section */}
          <div className="pt-3 border-t border-neutral-800/80 space-y-2.5">
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-neutral-400 uppercase tracking-wider flex items-center gap-1.5">
                <Key size={13} className="text-cyan-400" /> Predefined Accounts
              </span>
              <span className="text-[11px] text-neutral-500">1-click autofill & login</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {PREDEFINED_ACCOUNTS.map((acc) => {
                const Icon = acc.icon;
                const isSelected = activePreset === acc.email;
                return (
                  <div
                    key={acc.email}
                    onClick={() => handleSelectPreset(acc)}
                    className={`cursor-pointer rounded-xl border p-2.5 transition-all text-left flex flex-col justify-between ${
                      isSelected
                        ? `${acc.border} bg-neutral-950 shadow-md`
                        : "border-neutral-800 bg-neutral-950/60 hover:border-neutral-700"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-1 mb-1">
                      <span className="flex items-center gap-1.5 text-xs font-semibold">
                        <Icon size={13} className={acc.text} />
                        <span className={acc.text}>{acc.label}</span>
                      </span>
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-neutral-800 text-neutral-400 font-mono">
                        {acc.redirectUrl}
                      </span>
                    </div>

                    <div className="text-[11px] text-neutral-200 font-medium truncate">
                      {acc.name}
                    </div>
                    <div className="text-[10px] text-neutral-500 font-mono truncate">
                      {acc.email}
                    </div>

                    <div className="mt-2 pt-1.5 border-t border-neutral-800/60 flex items-center justify-between">
                      <span className="text-[10px] text-neutral-500 font-mono">
                        pw: <span className="text-neutral-400">{acc.password}</span>
                      </span>
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleQuickLogin(acc);
                        }}
                        className="text-[10px] font-semibold text-cyan-400 hover:text-cyan-300 flex items-center gap-0.5"
                      >
                        Quick Login <ChevronRight size={11} />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* API settings toggle */}
          <div className="pt-1 text-center">
            <button
              type="button"
              onClick={() => setShowApiConfig(!showApiConfig)}
              className="text-[11px] text-neutral-500 hover:text-neutral-300 transition-colors"
            >
              {showApiConfig ? "Hide API configuration" : `Connected to API: ${currentApi || "(relative)"} ⚙️`}
            </button>

            {showApiConfig && (
              <div className="mt-2 p-3 bg-neutral-950 rounded-xl border border-neutral-800 text-left space-y-2">
                <label className="text-[11px] text-neutral-400 font-medium">Backend API URL:</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={customApiBase}
                    onChange={(e) => setCustomApiBase(e.target.value)}
                    placeholder="https://neon-backend-xxxx.onrender.com"
                    className="flex-1 bg-neutral-900 border border-neutral-700 rounded-lg px-2.5 py-1.5 text-xs text-neutral-100 font-mono outline-none"
                  />
                  <button
                    type="button"
                    onClick={onSaveApiBase}
                    className="bg-cyan-500 hover:bg-cyan-400 text-neutral-950 text-xs font-semibold px-2.5 py-1.5 rounded-lg"
                  >
                    Save
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-5 text-center text-xs text-neutral-600">
          Neon Classes Task Tracker · RBAC Sequential Production Pipeline
        </div>
      </div>
    </div>
  );
}

/* ---------------------------------------------------------------- */
/* Main Application Component                                       */
/* ---------------------------------------------------------------- */

let toastCounter = 0;
const generateToastId = () => `toast_${++toastCounter}_${Date.now()}`;


export default function App() {
  const [token, setToken] = useState(() => {
    try {
      return localStorage.getItem("neon_auth_token") || null;
    } catch {
      return null;
    }
  });
  const [me, setMe] = useState(() => {
    try {
      const s = localStorage.getItem("neon_auth_user");
      return s ? JSON.parse(s) : null;
    } catch {
      return null;
    }
  });
  const [users, setUsers] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [view, setView] = useState("dashboard");
  const [toasts, setToasts] = useState([]);
  const [showCreate, setShowCreate] = useState(false);
  const [detailId, setDetailId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [busyStepId, setBusyStepId] = useState(null);
  const [fatalError, setFatalError] = useState(null);
  const [customApiBase, setCustomApiBase] = useState(() => getApiBase());
  const [authError, setAuthError] = useState(null);
  const [authLoading, setAuthLoading] = useState(false);

  const isAdmin = me?.role === "ADMIN";

  const getUserById = useCallback((id) => users.find((u) => u.id === id), [users]);

  const pushToast = useCallback((type, title, msg) => {
    const id = generateToastId();
    setToasts((p) => [...p, { id, type, title, msg }]);
    setTimeout(() => setToasts((p) => p.filter((t) => t.id !== id)), 4200);
  }, []);

  const fetchTasks = useCallback(async (authToken) => {
    const data = await apiFetch("/tasks", authToken);
    setTasks(data);
  }, []);

  const handleLogout = useCallback(() => {
    try {
      localStorage.removeItem("neon_auth_token");
      localStorage.removeItem("neon_auth_user");
    } catch {
      // ignore
    }
    setToken(null);
    setMe(null);
    setTasks([]);
    setDetailId(null);
    setShowCreate(false);
    window.location.hash = "#/login";
    pushToast("info", "Signed out", "You have returned to the sign in page.");
  }, [pushToast]);

  const handleLogin = async (email, password) => {
    setAuthLoading(true);
    setAuthError(null);
    try {
      const { access_token, user } = await apiFetch("/auth/login", null, {
        method: "POST",
        body: JSON.stringify({ email, password }),
      });
      try {
        localStorage.setItem("neon_auth_token", access_token);
        localStorage.setItem("neon_auth_user", JSON.stringify(user));
      } catch {
        // ignore
      }
      setToken(access_token);
      setMe(user);

      const targetHash = user.role === "ADMIN" ? "#/admin" : "#/employee";
      window.location.hash = targetHash;

      const [taskList, userList] = await Promise.all([
        apiFetch("/tasks", access_token),
        apiFetch("/users", access_token),
      ]);
      setTasks(taskList);
      setUsers(userList);
      setFatalError(null);

      pushToast(
        "success",
        `Welcome, ${user.name}!`,
        user.role === "ADMIN"
          ? "Admin Portal active (#/admin)"
          : `Employee Workspace active (#/employee)`
      );
    } catch (e) {
      setAuthError(e.message || "Invalid email or password.");
    } finally {
      setAuthLoading(false);
    }
  };

  /* Switch or authenticate as any seeded user (for Admin profile switcher) */
  const loginAs = useCallback(
    async (userId) => {
      try {
        const { access_token, user } = await apiFetch(`/auth/switch-user/${userId}`, null, {
          method: "POST",
        });
        try {
          localStorage.setItem("neon_auth_token", access_token);
          localStorage.setItem("neon_auth_user", JSON.stringify(user));
        } catch {
          // ignore
        }
        setToken(access_token);
        setMe(user);
        setDetailId(null);
        setShowCreate(false);

        const targetHash = user.role === "ADMIN" ? "#/admin" : "#/employee";
        window.location.hash = targetHash;

        await fetchTasks(access_token);
        pushToast(
          "info",
          "Switched Profile",
          `Now acting as ${user.name} (${ROLE_META[user.role]?.label || user.role})`
        );
        return access_token;
      } catch (e) {
        pushToast("error", "Switch failed", e.message);
      }
    },
    [fetchTasks, pushToast]
  );

  const loadData = useCallback(async () => {
    const savedToken = token || localStorage.getItem("neon_auth_token");
    if (!savedToken) return;
    const [taskList, userList] = await Promise.all([
      apiFetch("/tasks", savedToken),
      apiFetch("/users", savedToken),
    ]);
    setTasks(taskList);
    setUsers(userList);
    setFatalError(null);
  }, [token]);

  useEffect(() => {
    let ignore = false;
    const init = async () => {
      let savedToken = null;
      let savedUser = null;
      try {
        savedToken = localStorage.getItem("neon_auth_token");
        savedUser = localStorage.getItem("neon_auth_user");
      } catch {
        // ignore
      }

      if (!savedToken || !savedUser) {
        setToken(null);
        setMe(null);
        setLoading(false);
        if (window.location.hash !== "#/login") {
          window.location.hash = "#/login";
        }
        return;
      }

      try {
        const parsed = JSON.parse(savedUser);
        setToken(savedToken);
        setMe(parsed);

        const targetHash = parsed.role === "ADMIN" ? "#/admin" : "#/employee";
        if (!window.location.hash || window.location.hash === "#/login") {
          window.location.hash = targetHash;
        }

        const [taskList, userList] = await Promise.all([
          apiFetch("/tasks", savedToken),
          apiFetch("/users", savedToken),
        ]);
        if (ignore) return;
        setTasks(taskList);
        setUsers(userList);
        setFatalError(null);
      } catch (e) {
        if (ignore) return;
        if (e.status === 401 || e.status === 403) {
          try {
            localStorage.removeItem("neon_auth_token");
            localStorage.removeItem("neon_auth_user");
          } catch {
            // ignore
          }
          setToken(null);
          setMe(null);
          window.location.hash = "#/login";
        } else {
          setFatalError(e.message || "Couldn't reach the backend.");
        }
      } finally {
        if (!ignore) setLoading(false);
      }
    };

    init();
    return () => {
      ignore = true;
    };
  }, []);

  useEffect(() => {
    const onHash = () => {
      const h = window.location.hash;
      if (!token || !me) {
        if (h !== "#/login") {
          window.location.hash = "#/login";
        }
      } else {
        if (h === "#/login") {
          window.location.hash = me.role === "ADMIN" ? "#/admin" : "#/employee";
        } else if (h === "#/admin" && me.role !== "ADMIN") {
          pushToast(
            "error",
            "Access Denied",
            "Employees do not have access to the Admin Portal. Redirected to Employee Workspace."
          );
          window.location.hash = "#/employee";
        }
      }
    };
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, [token, me, pushToast]);

  const handleRetry = async () => {
    setLoading(true);
    setFatalError(null);
    try {
      await loadData();
    } catch (e) {
      setFatalError(e.message || "Couldn't reach the backend.");
    } finally {
      setLoading(false);
    }
  };

  const switchUser = async (id) => {
    await loginAs(id);
  };


  const createTask = async (title, description, assignments) => {
    setCreating(true);
    try {
      const result = await apiFetch("/tasks", token, {
        method: "POST",
        body: JSON.stringify({ title, description, assignments }),
      });
      setTasks((p) => [result.task, ...p]);
      pushToast("success", "Task created", result.message);
      setShowCreate(false);
    } catch (e) {
      pushToast("error", "Couldn't create task", e.message);
    } finally {
      setCreating(false);
    }
  };

  /* Step toggle with server-side validation */
  const toggleStep = async (taskId, stepId) => {
    setBusyStepId(stepId);
    try {
      const result = await apiFetch(`/tasks/${taskId}/steps/${stepId}`, token, {
        method: "PATCH",
      });
      setTasks((p) => p.map((t) => (t.id === taskId ? result.task : t)));
      pushToast("success", "Step updated", result.message);
      if (result.task_status_message) {
        const type = result.task_status_message.includes("auto-marked Done") ? "done" : "info";
        pushToast(
          type,
          type === "done" ? "Task complete" : "Task reopened",
          result.task_status_message
        );
      }
    } catch (e) {
      pushToast("error", e.status === 403 ? "Not allowed" : "Step locked", e.message);
    } finally {
      setBusyStepId(null);
    }
  };

  const detailTask = tasks.find((t) => t.id === detailId) || null;

  const stepsAll = tasks.reduce((a, t) => a + (t.steps?.length || 0), 0);
  const stepsDone = tasks.reduce(
    (a, t) => a + (t.steps || []).filter((s) => s.status === "DONE").length,
    0
  );
  const stats = [
    { label: "Total tasks", value: tasks.length, cls: "text-neutral-100" },
    {
      label: "In progress",
      value: tasks.filter((t) => t.status === "IN_PROGRESS").length,
      cls: "text-amber-300",
    },
    {
      label: "Completed",
      value: tasks.filter((t) => t.status === "DONE").length,
      cls: "text-emerald-300",
    },
    { label: "Steps done", value: `${stepsDone}/${stepsAll}`, cls: "text-cyan-300" },
  ];

  const NAV = [
    { key: "dashboard", label: "Dashboard", icon: LayoutDashboard },
    { key: "team", label: "Team", icon: Users },
  ];

  if (loading) {
    return (
      <div className="h-screen flex flex-col items-center justify-center bg-neutral-950 text-neutral-400 gap-3">
        <Loader2 className="animate-spin text-cyan-400" size={28} />
        <div className="text-sm font-medium">Connecting to Neon Classes API…</div>
      </div>
    );
  }

  if (fatalError) {
    const currentBase = getApiBase();
    return (
      <div className="h-screen flex flex-col items-center justify-center bg-neutral-950 text-neutral-300 gap-4 px-6 text-center">
        <div className="p-3 bg-red-950 border border-red-800 rounded-full text-red-400">
          <AlertCircle size={32} />
        </div>
        <div className="text-lg font-bold">Couldn't reach the backend</div>
        <div className="text-sm text-neutral-400 max-w-md">{fatalError}</div>

        <div className="text-xs text-neutral-400 bg-neutral-900 border border-neutral-800 p-3 rounded-xl max-w-md w-full text-left space-y-1">
          <div>Currently targeting: <span className="font-mono text-cyan-400">{currentBase || "(relative)"}</span></div>
          {currentBase.includes("localhost") && (
            <div className="text-amber-400 mt-1">
              ⚠️ The frontend is targeting <code>localhost:8000</code>. On Render, set your backend URL below or in Render's environment variables.
            </div>
          )}
        </div>

        <div className="w-full max-w-md bg-neutral-900 border border-neutral-800 p-3 rounded-xl flex flex-col gap-2">
          <label className="text-xs text-neutral-400 text-left font-medium">
            Backend URL (Render):
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              value={customApiBase}
              onChange={(e) => setCustomApiBase(e.target.value)}
              placeholder="https://neon-backend-xxxx.onrender.com"
              className="flex-1 bg-neutral-950 border border-neutral-700 rounded-lg px-3 py-1.5 text-xs text-neutral-100 font-mono focus:border-cyan-400 outline-none"
            />
            <button
              onClick={() => {
                if (customApiBase) {
                  localStorage.setItem("NEON_API_BASE", customApiBase.trim());
                } else {
                  localStorage.removeItem("NEON_API_BASE");
                }
                handleRetry();
              }}
              className="bg-cyan-500 hover:bg-cyan-400 text-neutral-950 font-semibold px-3 py-1.5 rounded-lg text-xs transition-colors shrink-0"
            >
              Save & Connect
            </button>
          </div>
        </div>

        <button
          onClick={handleRetry}
          className="mt-1 flex items-center gap-2 rounded-lg bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 px-4 py-2 text-sm font-semibold text-neutral-200 transition-colors"
        >
          <RefreshCw size={15} /> Retry Connection
        </button>
      </div>
    );
  }

  if (!token || !me) {
    return (
      <>
        <SignInPage
          onLogin={handleLogin}
          loading={authLoading}
          error={authError}
          clearError={() => setAuthError(null)}
          customApiBase={customApiBase}
          setCustomApiBase={setCustomApiBase}
          onSaveApiBase={() => {
            if (customApiBase) {
              localStorage.setItem("NEON_API_BASE", customApiBase.trim());
            } else {
              localStorage.removeItem("NEON_API_BASE");
            }
            pushToast("info", "Saved API Base", `Now targeting ${customApiBase || "(relative)"}`);
          }}
        />
        <ToastStack toasts={toasts} />
      </>
    );
  }

  return (
    <div
      className="h-screen overflow-hidden flex bg-neutral-950 text-neutral-100"
      style={{
        fontFamily:
          'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
      }}
    >
      <style>{CSS}</style>

      {/* §1 Fixed left sidebar */}
      <aside className="hidden md:flex md:flex-col w-60 shrink-0 border-r border-neutral-800">
        <div className="flex items-center gap-2.5 px-5 h-16 border-b border-neutral-800 shrink-0">
          <div
            className="h-8 w-8 rounded-lg bg-cyan-500 text-neutral-950 flex items-center justify-center"
            style={{ boxShadow: "0 0 20px rgba(34,211,238,0.4)" }}
          >
            <Zap size={17} strokeWidth={2.5} />
          </div>
          <div className="leading-tight">
            <div className="font-extrabold tracking-tight text-sm">NEON CLASSES</div>
            <div className="text-neutral-500 tracking-widest uppercase" style={{ fontSize: 10 }}>
              Task Tracker
            </div>
          </div>
        </div>

        <nav className="p-3 space-y-1">
          {NAV.map(({ key, label, icon: Icon }) => {
            const active = view === key;
            return (
              <button
                key={key}
                onClick={() => setView(key)}
                className={`w-full flex items-center gap-2.5 rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
                  active
                    ? "bg-neutral-900 text-cyan-300"
                    : "text-neutral-400 hover:text-neutral-100 hover:bg-neutral-900"
                }`}
              >
                <Icon size={16} /> {label}
              </button>
            );
          })}
        </nav>

        <div className="px-5 pt-4 pb-2 text-xs font-semibold uppercase tracking-widest text-neutral-600">
          Workflows
        </div>
        <div className="px-3 space-y-1">
          {WORKER_ROLES.map((r) => {
            const m = ROLE_META[r];
            const Icon = m.icon;
            return (
              <div
                key={r}
                className="flex items-center justify-between rounded-lg px-3 py-2 text-xs text-neutral-400"
              >
                <span className="flex items-center gap-2">
                  <Icon size={13} className={m.text} /> {m.label}
                </span>
                <span className="text-neutral-600">{WORKFLOWS_DISPLAY[r]} steps</span>
              </div>
            );
          })}
        </div>

        <div className="mt-auto p-4 border-t border-neutral-800 space-y-3">
          <div className="flex items-center justify-between text-xs">
            <span className="text-neutral-500 font-mono text-[11px]">
              {isAdmin ? "#/admin" : "#/employee"}
            </span>
            <span
              className={`px-2 py-0.5 rounded text-[10px] font-semibold border ${ROLE_META[me?.role]?.border} ${ROLE_META[me?.role]?.bg} ${ROLE_META[me?.role]?.text}`}
            >
              {ROLE_META[me?.role]?.label}
            </span>
          </div>
          <button
            onClick={handleLogout}
            className="w-full flex items-center justify-center gap-2 rounded-xl bg-neutral-900 hover:bg-red-950/40 border border-neutral-800 hover:border-red-800/80 text-neutral-400 hover:text-red-300 px-3 py-2 text-xs font-semibold transition-all"
          >
            <LogOut size={14} /> Sign Out
          </button>
          <div className="text-[10px] text-neutral-600 text-center">
            Neon Universe Pvt. Ltd. · Jaipur
          </div>
        </div>
      </aside>

      {/* Main Column */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Sticky Header */}
        <header
          className="shrink-0 border-b border-neutral-800 px-4 md:px-8 h-16 flex items-center justify-between gap-3"
          style={{ background: "rgba(10,10,11,0.85)", backdropFilter: "blur(8px)" }}
        >
          <div className="flex items-center gap-3 min-w-0">
            <div className="md:hidden h-8 w-8 rounded-lg bg-cyan-500 text-neutral-950 flex items-center justify-center shrink-0">
              <Zap size={16} strokeWidth={2.5} />
            </div>
            <div className="min-w-0">
              <h1 className="text-base md:text-lg font-bold tracking-tight truncate">
                {view === "dashboard" ? (isAdmin ? "All Tasks" : "My Tasks") : "Team"}
              </h1>
              <p className="text-xs text-neutral-500 hidden sm:block">
                {view === "dashboard"
                  ? `${tasks.length} task${tasks.length === 1 ? "" : "s"} · viewing as ${
                      ROLE_META[me?.role]?.label || "User"
                    }`
                  : `${users.length} members across 4 roles`}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 md:gap-3">
            <div className="md:hidden flex gap-1">
              {NAV.map(({ key, icon: Icon }) => (
                <button
                  key={key}
                  onClick={() => setView(key)}
                  className={`p-2 rounded-lg transition-colors ${
                    view === key ? "bg-neutral-900 text-cyan-300" : "text-neutral-500 hover:text-neutral-200"
                  }`}
                >
                  <Icon size={16} />
                </button>
              ))}
            </div>

            {isAdmin && (
              <button
                onClick={() => setShowCreate(true)}
                className="flex items-center gap-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-neutral-950 text-sm font-semibold px-3 py-2 transition-colors"
                style={{ boxShadow: "0 0 24px rgba(34,211,238,0.25)" }}
              >
                <Plus size={16} /> <span className="hidden sm:inline">New Task</span>
              </button>
            )}

            <div className="flex items-center gap-2 rounded-full border border-neutral-800 bg-neutral-900 pl-1 pr-3 py-1">
              <Avatar user={me} className="h-7 w-7 text-xs" />
              <div className="leading-tight hidden sm:block">
                <div className="text-xs font-semibold">{me?.name}</div>
                <div className={`text-xs ${ROLE_META[me?.role]?.text}`}>
                  {ROLE_META[me?.role]?.label}
                </div>
              </div>
            </div>

            <div className="hidden lg:flex items-center px-2.5 py-1 rounded-lg bg-neutral-900 border border-neutral-800 text-[11px] font-mono">
              {isAdmin ? (
                <span className="text-cyan-400 font-semibold">#/admin</span>
              ) : (
                <span className="text-violet-400 font-semibold">#/employee</span>
              )}
            </div>

            <button
              onClick={handleLogout}
              title="Sign Out"
              className="flex items-center gap-1.5 rounded-lg border border-neutral-800 bg-neutral-900 hover:bg-red-950/40 hover:border-red-800/80 text-neutral-400 hover:text-red-300 px-3 py-2 text-xs font-semibold transition-all"
            >
              <LogOut size={15} />
              <span className="hidden sm:inline">Sign Out</span>
            </button>
          </div>
        </header>

        {/* Scrollable Main Area */}
        <main className="flex-1 overflow-y-auto">
          <div className="max-w-5xl mx-auto px-4 md:px-8 py-6 space-y-6">
            {view === "dashboard" ? (
              <>
                {/* Role-Specific Workspace Banner */}
                {isAdmin ? (
                  <section className="rounded-2xl border border-cyan-900/50 bg-gradient-to-r from-cyan-950/30 via-neutral-900 to-neutral-900 p-4 sm:p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <div className="flex items-center gap-3.5">
                      <div className="h-11 w-11 rounded-xl bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 flex items-center justify-center shrink-0">
                        <Shield size={22} />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h2 className="text-base font-bold text-neutral-100">
                            Admin Production Portal
                          </h2>
                          <span className="font-mono text-[10px] px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                            #/admin
                          </span>
                        </div>
                        <p className="text-xs text-neutral-400 mt-0.5">
                          Full system control: create tasks, assign roles, and oversee all 13-step production pipelines.
                        </p>
                      </div>
                    </div>
                    <button
                      onClick={() => setShowCreate(true)}
                      className="flex items-center gap-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-neutral-950 text-xs sm:text-sm font-bold px-4 py-2.5 transition-colors shadow-lg shadow-cyan-500/20 shrink-0"
                    >
                      <Plus size={16} /> Create New Task
                    </button>
                  </section>
                ) : (
                  <section className="rounded-2xl border border-violet-900/50 bg-gradient-to-r from-violet-950/30 via-neutral-900 to-neutral-900 p-4 sm:p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <div className="flex items-center gap-3.5">
                      <div className="h-11 w-11 rounded-xl bg-violet-500/20 border border-violet-500/30 text-violet-300 flex items-center justify-center shrink-0">
                        {(() => {
                          const Icon = ROLE_META[me?.role]?.icon || PenLine;
                          return <Icon size={22} />;
                        })()}
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h2 className="text-base font-bold text-neutral-100">
                            {ROLE_META[me?.role]?.label} Workspace
                          </h2>
                          <span className="font-mono text-[10px] px-2 py-0.5 rounded bg-violet-950 text-violet-300 border border-violet-800">
                            #/employee
                          </span>
                        </div>
                        <p className="text-xs text-neutral-400 mt-0.5">
                          Welcome back, <strong className="text-neutral-200">{me?.name}</strong>! Showing only tasks assigned to your role ({tasks.length} active).
                        </p>
                      </div>
                    </div>
                    <div className="text-xs text-neutral-400 bg-neutral-950/80 border border-neutral-800 px-3 py-2 rounded-xl shrink-0">
                      Sequential RBAC: only complete your step when previous steps are done.
                    </div>
                  </section>
                )}

                {/* §3 Demo Role Switcher (calls /auth/switch-user) */}
                <section className="rounded-2xl border border-neutral-800 bg-neutral-900 p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="h-2 w-2 rounded-full bg-cyan-400 animate-pulse" />
                    <h2 className="text-xs font-semibold uppercase tracking-widest text-neutral-400">
                      Demo · Switch Profile
                    </h2>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {users.map((u) => {
                      const active = u.id === me?.id;
                      const m = ROLE_META[u.role] || ROLE_META.ADMIN;
                      const Icon = m.icon;
                      return (
                        <button
                          key={u.id}
                          onClick={() => switchUser(u.id)}
                          className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm transition-colors ${
                            active
                              ? `${m.bg} ${m.border} ${m.text}`
                              : "border-neutral-800 bg-neutral-950 text-neutral-400 hover:border-neutral-600 hover:text-neutral-200"
                          }`}
                        >
                          <Icon size={14} />
                          <span className="font-medium">{u.name}</span>
                          <span className="hidden sm:inline text-xs opacity-70">· {m.label}</span>
                        </button>
                      );
                    })}
                  </div>
                </section>

                {/* Dashboard Stats */}
                <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                  {stats.map((s) => (
                    <div key={s.label} className="rounded-2xl border border-neutral-800 bg-neutral-900 p-4">
                      <div className="text-xs uppercase tracking-widest text-neutral-500 mb-1">
                        {s.label}
                      </div>
                      <div className={`text-2xl font-bold tracking-tight ${s.cls}`}>{s.value}</div>
                    </div>
                  ))}
                </section>

                {/* Tasks Grid */}
                {tasks.length === 0 ? (
                  <section className="rounded-2xl border border-dashed border-neutral-800 p-12 flex flex-col items-center text-center gap-3">
                    <ClipboardList size={28} className="text-neutral-600" />
                    <div className="text-sm text-neutral-400">
                      {isAdmin
                        ? "No tasks yet. Create the first one to auto-generate its 13-step workflow."
                        : "No tasks assigned to you yet. The Admin assigns work from their dashboard."}
                    </div>
                    {isAdmin && (
                      <button
                        onClick={() => setShowCreate(true)}
                        className="mt-1 flex items-center gap-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-neutral-950 text-sm font-semibold px-3 py-2 transition-colors"
                      >
                        <Plus size={16} /> New Task
                      </button>
                    )}
                  </section>
                ) : (
                  <section className="grid gap-4 md:grid-cols-2">
                    {tasks.map((t) => (
                      <TaskCard
                        key={t.id}
                        task={t}
                        getUserById={getUserById}
                        onOpen={() => setDetailId(t.id)}
                      />
                    ))}
                  </section>
                )}
              </>
            ) : (
              /* Team View */
              <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {users.map((u) => {
                  const m = ROLE_META[u.role] || ROLE_META.ADMIN;
                  const assigned =
                    u.role === "ADMIN" ? [] : tasks.filter((t) => t.assignments?.[u.role] === u.id);
                  const roleSteps = assigned.flatMap((t) =>
                    (t.steps || []).filter((s) => s.role === u.role)
                  );
                  const sd = roleSteps.filter((s) => s.status === "DONE").length;
                  return (
                    <div
                      key={u.id}
                      className="rounded-2xl border border-neutral-800 bg-neutral-900 p-5 flex items-center gap-4"
                    >
                      <Avatar user={u} className="h-12 w-12 text-sm" />
                      <div className="min-w-0">
                        <div className="font-semibold tracking-tight">{u.name}</div>
                        <div className={`text-xs ${m.text}`}>{m.label}</div>
                        <div className="text-xs text-neutral-500 mt-1">
                          {u.role === "ADMIN"
                            ? `Oversees all ${tasks.length} tasks`
                            : `${assigned.length} task${assigned.length === 1 ? "" : "s"} · ${sd}/${
                                roleSteps.length
                              } steps done`}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </section>
            )}
          </div>
        </main>
      </div>

      {/* Modals & Toasts */}
      {showCreate && (
        <CreateTaskModal
          users={users}
          onClose={() => setShowCreate(false)}
          onCreate={createTask}
          pushToast={pushToast}
          creating={creating}
        />
      )}
      {detailTask && (
        <TaskDetailsModal
          task={detailTask}
          me={me}
          isAdmin={isAdmin}
          getUserById={getUserById}
          onClose={() => setDetailId(null)}
          onToggle={toggleStep}
          busyStepId={busyStepId}
        />
      )}
      <ToastStack toasts={toasts} />
    </div>
  );
}
